apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-github-tekton-060625x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-github-tekton-060625x 
  name: quarkus-github-tekton-060625x
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quarkus-github-tekton-060625x 
